ci: add step to set power bi variables per env

diff --git a/cicd/az-pipeline-reports-ci.yaml b/cicd/az-pipeline-reports-ci.yaml
--- a/cicd/az-pipeline-reports-ci.yaml
+++ b/cicd/az-pipeline-reports-ci.yaml
@@ -1,27 +1,34 @@
-
 steps:
-  - ${{ if eq(parameters.shouldRun, true) }}:
-    - script: |
-        echo "Checking number of rows set to zero"
-        RESULT=$(poetry run pbi check-num-rows-vars-zero)
-        echo $RESULT
-        if [[ $RESULT == Warning* ]] ;
-        then
-          echo "##vso[task.logissue type=warning;]$RESULT"
-        else
-          echo "##vso[task.logissue type=info]$RESULT"
-        fi
-      displayName: 'Check number of rows set to zero'
+  - ${{ if eq(parameters.shouldrun, true) }}:
+      - script: |
+          echo "checking number of rows set to zero"
+          result=$(poetry run pbi check-num-rows-vars-zero)
+          echo $result
+          if [[ $result == warning* ]] ;
+          then
+            echo "##vso[task.logissue type=warning;]$result"
+          else
+            echo "##vso[task.logissue type=info]$result"
+          fi
+        displayname: "check number of rows set to zero"
+        condition: eq(variables['getChangedFiles.pbi_changes], 'true')
 
-    - script: |
-        echo "Checking multi partitions are in place."
-        RESULT=$(poetry run pbi check-partitions)
-        echo $RESULT
-        if [[ $RESULT == Warning* ]] ;
-        then
-          echo "##vso[task.logissue type=error;]$RESULT"
-          exit 1
-        else
-          echo "##vso[task.logissue type=info]$RESULT"
-        fi
-      displayName: 'Check multi partitions'
+      - script: |
+          echo "checking multi partitions are in place."
+          result=$(poetry run pbi check-partitions)
+          echo $result
+          if [[ $result == warning* ]] ;
+          then
+            echo "##vso[task.logissue type=error;]$result"
+            exit 1
+          else
+            echo "##vso[task.logissue type=info]$result"
+          fi
+        displayname: "check multi partitions"
+        condition: eq(variables['getChangedFiles.pbi_changes], 'true')
+
+      - script: |
+          poetry run pbi set-pipeline-variables ${{ parameters.env }}
+          git commit -v -a --no-edit --amend
+        displayname: "Set Pipeline variables to env default"
+        condition: eq(variables['getChangedFiles.pbi_changes], 'true')
